FROM python:3.11-slim
LABEL maintainer="Abdur Rahman"

# Install Jupyter Notebook and dependencies in a single RUN command
RUN pip install --no-cache-dir jupyter

# Create a directory for the notebook
WORKDIR /notebooks

# Expose the Jupyter Notebook port
EXPOSE 8888

# Run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]