name: Docker Image CI

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from branch or tag
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          VERSION="${GITHUB_REF#refs/tags/}"
        elif [[ "${GITHUB_REF}" == refs/heads/release/* ]]; then
          VERSION="${GITHUB_REF#refs/heads/release/}"
        else
          VERSION="latest"
        fi
        echo "::set-output name=version::$VERSION"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/jupyter-notebook:${{ steps.vars.outputs.version }}
          ${{ secrets.DOCKER_USERNAME }}/jupyter-notebook:latest

