#!/bin/bash

# Navigate to the repository directory
#cd "$1" || exit

# Add all changes
git add "$1" 

# Commit changes with the provided message
git commit -m "$2"

# Stash changes if there are any
git stash

# Pull the latest changes
git pull origin main

# Apply stashed changes
git stash pop

# Push the committed changes
git push origin main
